INSERT INTO TB_TWITTER_DATA
(
	ID
	,TWEETER_ID
	,ACCOUNT_NAME
	,TWEET_TEXT
	,HASHTAGS
	,RETWEET_CNT
	,URL
	,DELETED_YN
	,DELETED_DT
	,CREATE_DT
	,UPDATE_DT
) 
VALUES (
	(SELECT UPPER(LEFT(UUID(), 8)))
	,@TWEETER_ID
	,@ACCOUNT_NAME
	,@TWEET_TEXT
	,@HASHTAGS
	,@RETWEET_CNT
	,@URL
	,'N'
	,NULL
	,(SELECT NOW())
	,NULL
) ON DUPLICATE KEY UPDATE 
	TWEET_TEXT = @TWEET_TEXT
	HASHTAGS = @HASHTAGS
	RETWEET_CNT = @RETWEET_CNT
	UPDATE_DT = (SELECT NOW())